#import "./../../fragments/ChatMessage/fragment.gql"

subscription OnMessage ($topic: String!) {
    onMessage(topic: $topic) {
        ... on Message {
            ...ChatMessage
        }
        ... on RemoveMessage {
            _id
        }
    }
}
