#import "./../ActivePlayer/fragment.gql"

fragment ActiveGame on GameSession {
    _id,
    name,
    observers,
    creator,
    status,
    winner,
    mover,
    timers {
        move
        choice
    }
    players {
        ...ActivePlayer
    }
}
