#import "api/apollo/fragments/ActivePlayer/fragment.gql"

fragment ActiveGame on GameSession {
    _id,
    name,
    observers,
    creator,
    status,
    winner,
    mover,
    timers {
        dice
        card
        dream
    }
    players {
        ...ActivePlayer
    }
}
