query GetUser($userId: ObjectId!) {
    user(_id: $userId) {
        _id
        role
        name {
            familyName
            givenName
        }
        nickname
        photos {
            url
        }
    }
}