#import "api/apollo/fragments/GameUser/fragment.gql"

fragment Statistic on Game {
    _id
    name
    createdAt
    winner {
        ...GameUser
    }
    tournament {
        _id
        name
    }
    players {
        ...GameUser
    }
}
