export * from 'api/apollo/queries/GetActiveGames';
export * from 'api/apollo/queries/GetCards';
export * from 'api/apollo/queries/GetMessages';
export * from 'api/apollo/queries/GetUserStatistic';
export * from 'api/apollo/queries/GetTournaments';
export * from 'api/apollo/queries/GetTournamentsStatistic';
export * from 'api/apollo/queries/GetUser';
export * from 'api/apollo/queries/GetVKRedirectUrl';
export * from 'api/apollo/queries/JoinGame';
